name: bookly
description: "Book app with clean architecture"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
